CREATE DATABASE CUST;
CREATE TABLE CUSTOMER
(
USERNAME VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
FNAME VARCHAR (50) NOT NULL,
DOB VARCHAR(50) NOT NULL,
PHN VARCHAR(50) NOT NULL,
IMG IMAGE
);
SELECT *  FROM CUSTOMER;


CREATE TABLE Guide
(
USERNAME VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
ADDR VARCHAR (50) NOT NULL,
MNO VARCHAR(50) NOT NULL,
LOC VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
AMNT VARCHAR(50) NOT NULL,
IMG IMAGE
);
SELECT *  FROM Guide;

CREATE TABLE TA
(
USERNAME VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
ADDR VARCHAR (50) NOT NULL,
LOC VARCHAR(50) NOT NULL,
MOB VARCHAR(50) NOT NULL,
WEB VARCHAR(50) NOT NULL,
PLACE VARCHAR(50) NOT NULL,
AMNT VARCHAR(50) NOT NULL,
IMG IMAGE
);
SELECT *  FROM TA; 

CREATE TABLE DRIVE
(
USERNAME VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
ADDR VARCHAR (50) NOT NULL,
LOC VARCHAR(50) NOT NULL,
MOB VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
CARNO VARCHAR(50) primary key NOT NULL,
CTYPE VARCHAR(50) NOT NULL,
CMODEL VARCHAR(50) NOT NULL,
IMG IMAGE
);
SELECT *  FROM DRIVE;


CREATE TABLE HOTEL
(
USERNAME VARCHAR(50) NOT NULL,
PASS VARCHAR(50) NOT NULL,
ADDR VARCHAR (50) NOT NULL,
LOC VARCHAR(50) NOT NULL,
MOB VARCHAR(50) NOT NULL,
WEB VARCHAR(50) NOT NULL,
HR VARCHAR(50) NOT NULL,
IMG IMAGE
);
SELECT *  FROM HOTEL; 

CREATE TABLE BOOK
(
USERNAME VARCHAR(50) NOT NULL,
SNAME VARCHAR(50) NOT NULL,
MOB VARCHAR (50) NOT NULL,
LOC VARCHAR(50) NOT NULL,
INFO1 VARCHAR(50) NOT NULL,
INFO2 VARCHAR(50) NOT NULL,
OCCUPATION VARCHAR(50) NOT NULL
);
SELECT *  FROM BOOK;

SELECT *  FROM CUSTOMER;

SELECT *  FROM Guide;

SELECT *  FROM TA; 

SELECT *  FROM DRIVE;

SELECT *  FROM HOTEL; 